### ISSUE TITLE
Possibly make this available as a nuget on nuget.org?

### ISSUE THREAD

**Issue by efreeman518** [azambrano/JsonDocumentPath#1]

**Comment by azambrano** [comment]
@efreeman518 there are missing two types of filters,. it is still an experimental project. I'm trying to find time to keep working on it

**Comment by onionhammer** [comment]
@azambrano I think that's probably OK if you release it as a pre-release package. Maybe try to find a few more part-time contributors to help you keep up with eventual demand or namespace it so it makes it clear this is an stop-gap?

**Comment by azambrano** [comment]
@efreeman518 @onionhammer I've already published the alpha version on Nuget. https://www.nuget.org/packages/JsonDocumentPath

**Comment by Laiteux** [comment]
Most likely not the right place to do so, but I wanted to thank you for this library.

**Comment by AraHaan** [comment]
@azambrano is this maintained, I need to create a PR for .NET 6 as well on .NET 6+ targets S.T.J should never be referenced manually as it comes from the Microsoft.NETCore.App framework pack. As such this package will need an 1.0.3 version pushed that incorporates that change.

Sorry for noticing this but it is an issue for me as I use it with Remora.Discord and it copies needless assemblies to my build outputs which waste disc space and network downloading the microsoft packages provided by default.
